### ISSUE TITLE
Bug: Banner covers Breadcrumbs in Reading Mode

### ISSUE THREAD

**Issue by bladeacer** [HandaArchitect/obsidian-banner-snippet#12]
### Replicating the issue
https://github.com/user-attachments/assets/dc919b2d-567f-4e76-87e6-4d3abc9249b5

#### CSS Snippet that fixes this
```css
body:where(.theme-dark):has(*.banner) div.markdown-reading-view div.BC-trail {
    transform: translateY(var(--banner-height));
    padding: 5px;
}
```

The padding is just personal preference.

**Comment by bladeacer** [comment]
This code might work better

```css
body:where(.theme-dark):has(*.banner) div.markdown-reading-view {
    & div.BC-NextPrev-Container{
        transform: translateY(var(--banner-height));
        margin: 5px;
    }
}
```
